CleverCooks/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('User.urls')),
     path('',include('Recipe.urls'))
]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Recipe/urls.py
from django.urls import path,include
from Recipe import views


urlpatterns = [
    path('',views.index,name='index'),
    path('postrecipe',views.postrecipe,name='postrecipe'),
    path('recipes',views.recipes,name='recipes'),
    path('recipe_desc/<int:id>',views.recipe_desc,name='recipe_desc'),
    path('aboutus',views.aboutus,name='aboutus'),
    path('search',views.search,name='search'),
]  

User/urls.py
from User import views
from django.urls import path,include

urlpatterns = [
    path('register',views.register,name='register'),
    path('login',views.loginpage,name='login'),
    path('profile/<str:username>',views.profile,name='profile'),
    path('logout',views.logoutUser,name='logout'),
    path('editprofile',views.editprofile,name='editprofile'),
    path('account-verify/<slug:token>',views.account_verify,name='account_verify')
]  

Recipe/models.py
from django.db import models
from autoslug import AutoSlugField
from django.contrib.auth.models import User
    

class Recipe(models.Model):
    #recipe_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    coverImage= models.ImageField(null=True, blank=True)
    serves = models.CharField(max_length=50)
    time = models.CharField(max_length=50)
    ingredients = models.TextField()
    instructions = models.TextField()
    #pub_date = models.DateField()

    def __str__(self):
        return self.title

class Newsletter(models.Model):
    emailaddress = models.EmailField(max_length = 254)

User/models.py
from django.db import models
from django.contrib.auth.models import User

class Verification(models.Model)  :
    user = models.OneToOneField(User, on_delete=models.CASCADE)  
    token = models.CharField(max_length=150)
    verify = models.BooleanField(default=False)
    

User/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.models import User
from django.contrib.auth import password_validation
class Register(UserCreationForm):
    password1 = forms.CharField(
            label = 'Password',
            strip = False,
            widget = forms.PasswordInput(attrs={'autocomplete':'new-password'}),
    )
    password2 = forms.CharField(
            label = 'Confirm Password',
            strip = False,
            widget = forms.PasswordInput(attrs={'autocomplete':'new-password',}),
    )

    class Meta:
        model = User
        fields = ('id','username','first_name','last_name','email','password1','password2')
        field_classes = {'username':UsernameField}

Recipe/views.py
from django.shortcuts import render,redirect, HttpResponse
from .models import Recipe, Newsletter
from django.views import View

def index(request):
    recipes = Recipe.objects.all()
    if request.method == 'POST':
         emailaddress = request.POST['emailaddress']
         newsletter= Newsletter(emailaddress=emailaddress)
         newsletter.save()
    return render(request,'index.html',{'recipes':recipes})

def aboutus(request):
    return render(request,'aboutus.html')

def postrecipe(request):
    if request.method == 'POST':
        title = request.POST['title']
        description = request.POST['description']
        coverImage = request.POST['coverImage']
        serves = request.POST['serves']
        time = request.POST['time']
        ingredients = request.POST['ingredients']
        instructions = request.POST['instructions']
        recipe = Recipe(title=title,description=description, coverImage=coverImage,serves=serves,time=time,ingredients=ingredients,instructions=instructions)
        recipe.save()
        return redirect('recipes')
    return render(request,'post_recipe.html')


def recipes(request):
    recipes = Recipe.objects.all()
    return render(request,'recipes.html',{'recipes':recipes})

def recipe_desc(request, id):
    recipedetails = Recipe.objects.filter(id = id)[0]
    recipes = Recipe.objects.all()
    context = {'recipedetails' : recipedetails , 'recipes':recipes}
    return render(request,'recipe_desc.html', context)

def search(request):
    query = request.GET['query']
    recipes = Recipe.objects.filter(title__icontains=query)
    params = {'recipes' : recipes}
    return render(request,'search.html',params)

User/views.py
from django.shortcuts import render, redirect
from .forms import Register
from .models import Verification
import uuid
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User


def register(request):
    if request.user.is_authenticated:
        return redirect('index')
    else:
        form = Register()
        if request.method == 'POST':
            form = Register(request.POST)
            if form.is_valid():
                new_user = form.save()
                uid = uuid.uuid4()
                verification_obj = Verification(user=new_user, token=uid)
                verification_obj.save()
                send_reg_email(new_user.email, uid)
                messages.success(
                    request, "Your Account Created! Please verify your account check your email")
                return redirect('/login')

    context = {'form': form}
    return render(request, 'register.html', context)


def send_reg_email(email, token):
    subject = 'Verify Email'
    message = f'Hello user! Click on the below link to verify your email http://127.0.0.1:8000/account-verify/{token}'
    from_email = settings.EMAIL_HOST_USER
    recipient_list = [email]
    send_mail(subject=subject, message=message,
              from_email=from_email, recipient_list=recipient_list)


def loginpage(request):
    if request.user.is_authenticated:
        return redirect('index')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            verify = Verification.objects.get(user=user)
            if verify.verify:
                if user is not None:
                    login(request, user)
                    return redirect('index')
                else:
                    messages.info(request, 'Username or Password is incorrect')

        context = {}
        return render(request, 'login.html', context)


def profile(request,username):
    user = User.objects.filter(username = username)[0]
    return render(request, 'profile.html',{'user':user})


def logoutUser(request):
    logout(request)
    return redirect('login')


def account_verify(request, token):
    pf = Verification.objects.filter(token=token).first()
    pf.verify = True
    pf.save()
    messages.success(
        request, "Your Account has been verified, Now you can login")
    return redirect('/login')

def editprofile(request):
    return render(request,'editprofile.html')

Recipe/templates/aboutus.html
{% extends "basic.html" %}
{% block title %}About Us{% endblock title %}
{% block body %}
{% load static %}
    <div class="container">
        <div class="row">
            <div class="col-10">
                <center><h2>About Us</h2></center>
                <h3>Namaste!</h3>
                <p>We are glad that you are here and thank you for stopping by on CleverCook's Recipes. -a blog which has pure vegetarian recipes, mostly Indian but some World Cuisine as well.</p>
                <p>Most of the recipes are in step by step pictorial guide. They are easy to understand and relate too. Some recipes have short videos with the stepwise photo guide.</p>
                <h3>About The Recipes</h3>
                <p>We have 1800 vegetarian recipes shared in this span of 1 year and is one of the largest collection of pure Indian vegetarian recipes which have been tried and tested and presented with step by step photos.</p>
                <p>The recipes are also shared with many tips and suggestions so that it is easier for anyone to make them easily.</p>
                <p>Many of our blog fans, readers and patrons love our recipes. We are also grateful to our readers for giving us blessings, positive vibes and good wishes.</p>
                <p>Positive energy does make a difference. The testimonial to this fact is the hundreds of positive comments, reviews and mentions we have on our popular recipes</p>
                <p>All the recipes are tried and tested in our kitchen first and then only shared on the blog. I keep the homemaker in mind and make the recipes. So that it is easy and one does not have to hunt around for ingredients – specifically ingredients which are not easily available in India.</p>
            </div>
            <div class="col-2">
                <div class="card" style="width: 18rem;">
                    <img src="static/denish.png" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">Denish Shihora</h5>
                      <p class="card-text">Hi, I'm <strong>Denish Shihora</strong>. I'm currently studying in CGPIT, Uka Tarsadiya University. I'm frontend devloper, currently learning Web Development With React.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-10">
                
                <p>The recipes shared are posted by some users and also taken from our families, relatives, friends. Some recipes are adapted from cookbooks. </p>
                <h3>Our Food Motto</h3>
                <p>We always prefer home cooked food whether it is making a simple Pizza or a loaf of bread or Chocolate Cake. We believe in cooking with fresh ingredients that are easily available.</p>
                <p>We avoid using heavily processed food or junk food. As a result we have sound health in our family. Eat healthy and stay healthy is our motto.</p>
                <p>On the blog you will find many healthy recipes made with whole grains and cereals. Even in many of my baking recipes, I have used healthy ingredients wherever possible.</p>
                <p>Even before I started to blog, I would buy organic and this habit has stayed even today. All our grocery stuff is organic produce from grains to sugar and flours.</p>
                <p>We even purchase organic vegetables and fruits. I cannot get all the vegetables & fruits organic in India. But I do buy whatever we can. Hence you will see fewer gourmet fruits or imported vegetables recipes on the blog.</p>
                <p>We buy local vegetables and fruits to ensure that this supports the farmers of our country.</p>
                <p>We also make sure to share some regional recipes made from rare ingredients or veggies which are not very popular or well known. We have tried to share at least one recipe of such an ingredient. E.g. We have covered many gourd varieties.</p>
                <h3>Using Recipes</h3>
                <p>If you have made and liked our recipe and want to add it in your website, blog or make a youtube video. Then please do the following:</p>
            </div>
            <div class="col-2">
                <div class="card" style="width: 18rem;">
                    <img src="static/Dhruv.jpg" class="card-img-top" alt="..." height=350px>
                    <div class="card-body">
                      <h5 class="card-title">Dhruv Bundheliya</h5>
                      <p class="card-text">Hi, I'm <strong>Dhruv Bundheliya</strong>. I'm currently studying in CGPIT, Uka Tarsadiya University. I'm Backend Devloper,.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-10">
                
                
                <p>1.  Write the recipe method or instructions in your own words instead of copying and pasting ours.</p>
                <p>2. Do write your own titles and headings. Please do not copy ours.</p>
                <p>3. Also do credit the recipe author that is myself (dassana) by name and provide a real link back to the source recipe page.</p>
                <p>It is a good practice to write the recipe in your own words and give a real link back to the author and the recipe source. It maintains your credibility and authenticity not only with your readers but deep down you will also feel good. Honesty and sincerity are two best friends one should never leave.</p>

                <h3>Get In Touch</h3>
                <p>You can email us at clevercooks@gmail.com if you have any query which you are not comfortable sharing in the comment or want to send us a photo of any recipe you made from the website.</p>
            </div>
            <div class="col-2">
                <div class="card" style="width: 18rem;">
                    <img src="static/milan.png" class="card-img-top" alt="..." height=300px>
                    <div class="card-body">
                      <h5 class="card-title">Milan Polara</h5>
                      <p class="card-text">Hi, I'm <strong>Milan Polara</strong>. I'm currently studying in CGPIT, Uka Tarsadiya University. I'm frontend devloper, currently learning Web Development With React.</p>
                    </div>
                </div>
            </div>
        </div>    
    </div>
    {% endblock body %}

Recipe/templates/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    <title>{% block title %}{% endblock title %}</title>
    <style>{% block style %}{% endblock style %}</style>
</head>
<body>
{% load static %}

{% include "header.html" %}
<br>
<br>
<br>
{% block body %}{% endblock body %}
{% include "footer.html" %}
</body>
</html>

Recipe/templates/footer.html
 <style>
   @import
url('https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&family=Roboto:wght@100;300;400;500;700;900&display=swap');
*,
*:after,
*:before {
-webkit-box-sizing: border-box;
box-sizing: border-box;
margin: 0;
padding: 0;
}

:active,
:hover,
:focus {
outline: 0 !important;
outline-offset: 0;
}
a{
color: #555;
}

a:hover {
text-decoration: none;
}



ul,
ol {
margin: 0;
padding: 0;
}


/*===== Variable Define =====*/
:root {
--primary-color: #A82C48;
--secondry-color: #43121d;
--third-color: #f98169;
--white-color: #fff;
--text-color: #555;
--text-gray: #999;
--black-color: #000;
--primary-font: "Roboto", sans-serif;
--secondry-font: 'Quicksand', sans-serif;
}

html {
scroll-behavior: smooth;
}

body {
font-family: var(--primary-font);
font-size: 100%;
font-weight: 400;
}

/*
=========================================
Custom Scrollbar
=========================================
*/

::-webkit-scrollbar {
width: 0.625rem;
}
::-webkit-scrollbar-track {
background: var(--white-color);
}
::-webkit-scrollbar-thumb {
background:var(--primary-color);
}

/*
==========================================
Custom CSS Design
==========================================
*/

h1 {
font-size: 3rem;
font-weight: 900;
margin-bottom: 3rem;
color: var(--secondry-color);
}

h2 {
font-weight: 700;
font-size: 2.25rem;
text-transform: capitalize;
font-family: var(--secondry-font);
color: var(--secondry-color);
line-height: 3rem;

}

h4 {
color: var(--secondry-color);
font-family: var(--secondry-font);
text-transform: capitalize;
font-size: 18px;
font-weight: 800;
margin-bottom: 0.5rem;
}

h5 {
color: var(--primary-color);
text-transform: capitalize;
font-family: var(--secondry-font);
font-size: 1rem;
font-weight: 700;
margin-bottom: 0.5rem;
}

p {
font-size: 1rem;
color: var(--text-color);
font-weight: 400;
line-height: 1.75rem;
letter-spacing: 1px;
}

.main-btn {
display: inline-block;
padding: 0.625rem 1.875rem;
line-height: 1.5625rem;
background-color: var(--primary-color);
border: 0.1875rem solid var(--primary-color);
color: var(--white-color);
font-size: 0.9375rem;
font-weight: 600;
text-transform: capitalize;
box-shadow: 0px 2px 10px -1px rgb(0 0 0 / 19%);
-webkit-transition: all .4s ease-out 0s;
-o-transition: all .4s ease-out 0s;
-moz-transition: all .4s ease-out 0s;
transition: all .4s ease-out 0s;
}

.white-btn {
padding: 0.625rem 1.875rem;
line-height: 25px;
background-color: var(--white-color);
border: 0.1875rem solid var(--white-color);
color: var(--text-color);
font-size: 0.9375rem;
font-weight: 600;
text-transform: capitalize;
box-shadow: 0px 2px 10px -1px rgb(0 0 0 / 19%);
-webkit-transition: all .4s ease-out 0s;
-o-transition: all .4s ease-out 0s;
-moz-transition: all .4s ease-out 0s;
transition: all .4s ease-out 0s;
}

.main-btn:hover {
background-color: transparent;
color: var(--primary-color);
}

.white-btn:hover {
background-color: transparent;
color: var(--primary-color);
border-color: var(--primary-color);
}

.wrapper {
padding-top: 8.25rem;
padding-bottom: 8.25rem;
}

.text-content {
width: 70%;
margin: auto;
}

.counter-section h2,
.testimonial-section h2,
.book-food-text h2 {
color: var(--white-color);
}




/*
==========================================
top-banner Design
==========================================
*/
.top-banner{
width:100%;
background: url('static/images/bg/bg-1.jpg') no-repeat center;
background-size:cover;
padding:16.875rem 0 9.375rem;
font-family: var(--secondry-font);
}


.carousel-item {
height: 24rem;
background: #000;
}
.carousel-inner{
height: 550px;
}
*/
==========================================
counter Design
==========================================
*/
.counter-section{
background-color: var(--primary-color);
padding:2.5rem 0;
}
.counter-section p{
color:var(--white-color);
text-transform: uppercase;
}


/*
==========================================
about section Design
==========================================
*/
.about-section{
background: var(--white-color);
}
.about-section .card,
.about-section .card img{
border-radius: 0.625rem;
}
.about-section .text-sec{
padding-left:2rem;
}

/*
==========================================
food type section Design
==========================================
*/
.food-type{
padding-top:3.25rem;
}
.food-type ul li{
font-size:1rem;
color:var(--text-color);
line-height: 32px;
position:relative;
margin-left: 30px;
}
.food-type ul li::before{
position:absolute;
left:-2.1875rem;
color:var(--primary-color);
font-size: 1.25rem;
font-family: "Font Awesome 5 Free";
content:'\f00c';
display:inline-block;
padding-right:3px;
vertical-align:middle;
font-weight: 900;
}
.story-section{
width:100%;
height:28.125rem;
background: url('static/images/bg/bg-2.jpg') no-repeat center;
background-size: cover;
padding-top:100px;
text-align: center;
}
.story-section h2{
color:var(--primary-color);
}

/*
==========================================
explore food section Design
==========================================
*/
.explore-food .card{
border:none;
background-color: transparent;
border-radius: 0.9375rem;
}
.explore-food .card img{
border-radius: 0.9375rem;
object-fit: cover;
}
.explore-food .card span{
display:block;
font-size: 1.5rem;
font-weight: 700;
color:var(--primary-color);
padding-bottom:1rem;
border-bottom:0.0625rem solid #eee;
}
.explore-food .card span del{
color:var(--text-gray);
margin-left:0.5rem;
}


/* Form Control */
.newsletter{
width:55%;
margin:0 auto;
}
.newsletter .form-control{
height:3.225rem;
padding:0 1.25rem;
font-size: 0.875rem;
width:100%;
border:none;
border-radius: 0;
background:transparent;
border:0.1875rem solid var(--text-gray);
color:var(--black-color);
font-weight: 700;
}
.newsletter .form-control:hover,
.newsletter .form-control:focus{
outline:none;
box-shadow: none;
border-color:var(--primary-color);
}

/*
==========================================
footer section Design
==========================================
*/
.footer{
background: var(--black-color);
padding-bottom: 0px;
margin-left: -100px;
margin-right: -100px;
}
.footer .footer-link{
font-size:1rem;
color:var(--white-color);
padding:0 1.875rem;
}
.footer .footer-link:hover{
color:var(--white-color) !important;
}
.footer a i{
font-size: 1.5rem;
color:var(--white-color);
padding:0 1rem;
}



/*
============================
Responsive Design
============================
*/
@media (max-width:1024px) {

/* about section */

}

@media (max-width: 991px) {

/*custom classes */
.text-content{
width:100%;
}


/* navbar brand */
.navigation-wrap .navbar-brand img{
height:3.8125rem;
}
.navigation-wrap{
text-align: center;
background-color: var(--white-color);
}
.navigation-wrap .nav-link{
line-height: 1.875rem;
}
/* Banner Design */
.top-banner{
padding:9.375rem 0 9.375rem;
}

/* carousel design */
.testimonial-section .carousel-item .carousel-caption p{
padding:0;
}

}

@media (max-width: 767px) {

/* custom css */
h1{
font-size:2.8rem;
}
h2{
font-size:2rem;
line-height: 2.0625rem;
}


/* top banner */
.top-banner{
padding:10.875rem 0 9.375rem;
}


/* story section */
.story-section{
height:auto;
padding:3rem 0;
}


/* carousel design */
.testimonial-section .carousel-item{
padding:11rem 3.125rem;
}

/* newslettar */
.newsletter{
width:75%;
}
.newsletter .main-btn{
width:100%;
margin-top:1rem;
}

/* footer link */
.footer .footer-link,
.footer a i{
padding:0 0.7rem;
}

}

@media (max-width:330px) {

/* carousel design */
.testimonial-section .carousel-item{
padding:13rem 3.125rem;
}

}
 </style>
  <footer id="footer">
    <div class="footer py-5">
        <div class="row">
          <div class="col-md-12 text-center">
            <a class="footer-link" href="#">Register</a>
            <a class="footer-link" href="#">Forum</a>
            <a class="footer-link" href="#">Affiliate</a>
            <a class="footer-link" href="#">FAQ</a>
            <div class="footer-social pt-4 text-center">
              <a href="#"><i class="fab fa-facebook-f"></i></a>
              <a href="#"><i class="fab fa-twitter"></i></a>
              <a href="#"><i class="fab fa-youtube"></i></a>
              <a href="#"><i class="fab fa-dribbble"></i></a>
              <a href="#"><i class="fab fa-linkedin"></i></a>
              <a href="#"><i class="fab fa-instagram"></i></a>
            </div>
          </div>
          <div class="col-sm-12">
            <div class="footer-copy">
              <div class="copy-right text-center pt-5">
                <p class="text-light">© 2021. Foodies. All rights reserved.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>

Recipe/templates/header.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
</head>

<body>
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand mx-1" href="/">CleverCooks</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
        aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px">
          <li class="nav-item mx-1">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item mx-1">
            <a class="nav-link" href="/recipes">Recipes</a>
          </li>
          <li class="nav-item mx-1">
            <a class="nav-link" href="/aboutus">About Us</a>
          </li>
          <li class="nav-item mx-1">
            <a class="nav-link" href="#newslettar">Contact Us</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle mx-1" href="" id="navbarScrollingDropdown" role="button"
              data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
              {% if request.user.is_authenticated %}
              <li><a class="dropdown-item" href="/profile/{{user.username}}">Profile</a></li>
              <li>
                <hr class="dropdown-divider" />
              </li>
              <li><a class="dropdown-item" href="/postrecipe">Post</a></li>
              <li>
                <hr class="dropdown-divider" />
              </li>
              <li><a class="dropdown-item" href="/logout">Sign Out</a></li>
              {% else %}
              <li><a class="dropdown-item" href="/register">Sign Up</a></li>
              <li>
                <hr class="dropdown-divider" />
              </li>
              <li><a class="dropdown-item" href="/login">Sign In</a></li>

              {% endif %}
            </ul>
          </li>
        </ul>
        <form method="GET" action="search" class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query" id="query"/>
          <button class="btn btn-outline-success" type="submit">
            Search
          </button>
        </form>
      </div>
    </div>
  </nav>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</html>

Recipe/templates/post_recipe.html
{% extends "basic.html" %}
{% block title %}CleverCooks | Post-Recipe{% endblock title %}
{% block body %}
  <div class="container">
    <div class="card border-dark text-dark bg-light mb-3">
      <div class="card-header">
        Post Recipe
      </div>
      <form action="" method="POST" >
        {% csrf_token %}
      <div class="card-body">
        <strong><p class="card-title"><label for="id_title">Title:</label></p></strong>
        <input type="text" name="title" maxlength="200" required id="id_title">
      </div>
      <div class="card-body">
        <strong><p class="card-title"><label for="id_description">Description:</label></p></strong>
        <textarea name="description" cols="40" rows="10" required id="id_description"></textarea>
      </div>
      <div class="card-body">
        <strong><p class="card-title"><label for="id_coverImage">Cover Image:</label></p></strong>
        <input type="file" name="coverImage" accept="image/*" required id="id_coverImage">
      </div>
      <div class="card-body">
        <strong><p class="card-title"><label for="id_serves">Serves:</label></p></strong>
        <input type="text" name="serves" maxlength="50" required id="id_serves">
      </div>
      <div class="card-body">
        <strong><p class="card-title"><label for="id_time">Time:</label></p></strong>
        <input type="text" name="time" maxlength="50" required id="id_time">
      </div>
      <div class="card-body">
        <strong><p class="card-title"><label for="id_ingredients">Ingredients:</label></p></strong>
        <textarea name="ingredients" cols="40" rows="10" required id="id_ingredients"></textarea>
      </div>
      <div class="card-body">
        <strong><p class="card-title"><label for="id_instructions">Instructions:</label></p></strong>
        <textarea name="instructions" cols="40" rows="10" required id="id_instructions"></textarea><br>
      </div>
      <div class="card-footer text-muted">
        <input type="submit" value="Submit" class="btn btn-primary" />
      </div>
      </form>
    </div>
  </div>
  {% endblock body %}

    <!--<div class="col-sm-12">
      <form action="" method="POST" >
        {% csrf_token %}
        <br>

        <label for="id_title">Title:</label>
        <br>
        <input type="text" name="title" maxlength="200" required id="id_title">
        <br>
        <label for="id_description">Description:</label><br>
        <textarea name="description" cols="40" rows="10" required id="id_description"></textarea><br>

        <label for="id_coverImage">Cover Image:</label><br>
        <input type="file" name="coverImage" accept="image/*" required id="id_coverImage"><br>

        <label for="id_serves">Serves:</label><br>
        <input type="text" name="serves" maxlength="50" required id="id_serves"><br>

        <label for="id_time">Time:</label><br>
        <input type="text" name="time" maxlength="50" required id="id_time"><br>

        <label for="id_ingredients">Ingredients:</label><br>
        <textarea name="ingredients" cols="40" rows="10" required id="id_ingredients"></textarea><br>

        <label for="id_instructions">Instructions:</label><br>
        <textarea name="instructions" cols="40" rows="10" required id="id_instructions"></textarea><br>

        <input type="submit" value="Submit" class="btn btn-primary" />
      </form>
    </div>
  </div>-->
  